## Домашнее задание

**Задание 1** 
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

P.S. Продолжаю не понимать логику того что делаю. Про вектора и углы из лекции понял, а остальное. вроде бы матрицы это списки признаков - ОК. Но зачем их надо создавать вручную, зачем пересчитывать диагонали. Есть же какая-то реальная простая задача которую надо решить таким способом. Не знаю, для тупых как я: Маша слушает Земфиру, Гриша слушает Стинга. Создайте матрицу и перемножьте ее по диагонали. Ответ в голове похож на нецензурный вариант слова зачем. Ну нагуглил я решение и куда его засунуть. К чему применить? 

In [1]:
import numpy as np

In [2]:
n = int(input('Введите число n: '))
array_ = np.arange(0, n)
array_ = array_[::-1]
print(array_)

Введите число n= 10
[9 8 7 6 5 4 3 2 1 0]


numpy.ndarray

**Задание 2** Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
n = int(input('Введите число n: '))
array_ = np.arange(0, n)
array_ = array_[::-1]
matrix_ = np.diag(array_)
print(matrix_)
summa_=np.trace(matrix_)
summa_

Введите число n = 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

**Задание 3** 

Решите систему уравнений: 
4x + 2y + z = 4
x + 3y = 12 
5y + 4z = -3

#P.s. говорилось что нетология научит даже гуманитаря. Ну ОК, просто я даже близко не знаю что такое линейные уравнения. Но #бестолково нагуглить решение могу. Что это такое? Где это применяется? Как это выучить? В общем чем дальше тем меньше я #понимаю смысл того что гуглю. 

In [4]:
from numpy import linalg
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [6]:
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

True

**Задание 4**

В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:
Матрица в виде numpy array

In [5]:
#пример как прикрепить фотографию
from IPython.display import Image
Image("user_matrix.JPG")

In [7]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [8]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [11]:
def cosine( a, b ):
    """    расчет cos. угла между векторами a, b     """
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )    
    return np.dot( a, b ) / ( aLength * bLength )

In [12]:
max_cos = -2
max_id = 0
for i,user in enumerate(users_stats):
    temp = cosine(user,next_user_stats)
    if temp > max_cos:
        max_cos = temp
        max_id = i
print(f'Id самого похожего пользователя - {max_id+1}')

Id самого похожего пользователя - 8
